### ISSUE TITLE
Just how to install it from Filza?

### ISSUE THREAD

**Issue by shayshtern** [finngaida/DayNightSwitch#8]
Help will be so greatful !! 
Please🙂! 
Good day to all,
Shay Shtern.

**Comment by finngaida** [comment]
I don't have any jailbroken devices at the moment, but you can try to install the .deb from the [release](https://github.com/finngaida/DayNightSwitch/releases/tag/1.0.2) section and let me know if it works.
I'll put an update on BigBoss then

**Comment by shayshtern** [comment]
I tried and it's not working.  Also the preference in the setting isn't loading.

**Comment by shayshtern** [comment]
I have a jailbroken iPhone XS Max (iPhone 11 ,6) - but I don't have Mac to compile the new code for arm64e👨🏻‍💼

**Comment by shayshtern** [comment]
Hooooo... It's a new Deb, let me try!

**Comment by shayshtern** [comment]
@finngaida You can Post it, It's working.
Really nice. Thank you.

**Comment by finngaida** [comment]
Submitted to Optimo
